services:
  _defaults:
    autoconfigure: true
    public: false

  contao.themecompiler.list:
    class: Oveleon\ContaoThemeCompilerBundle\Command\ThemeListCommand
    arguments:
      - '@contao.framework'

  contao.themecompiler.compile:
    class: Oveleon\ContaoThemeCompilerBundle\Command\ThemeCompileCommand
    arguments:
      - '@contao.framework'
